### ISSUE TITLE
Question about Stage1 dataset

### ISSUE THREAD

**Issue by Eden-yy** [DaSESmartEdu/ErrorCLR#1]
Hello,

After reading your paper, I'm very excited and eager to give it a try. However, I've encountered some confusion during my research and would greatly appreciate your guidance. I've noticed that in Stage 1, both during pretraining and fine-tuning, it seems that they don't use the same dataset, even though they both involve handling pairs of similar code. I would like to understand the differences between these two datasets. Does the "error_pair" dataset exclusively consist of pairs of similar code?

Thanks in advance!

**Comment by sqhan-Husky** [comment]
Hi @Eden-yy,

Thank you for your attention to our work. 

The difference between the two datasets is that in the pretraining dataset, we pair one buggy program with multiple reference programs of various similarities, while in the finetuning dataset, we only pair a buggy program with the most similar reference program. We use different datasets for pretraining and finetuning due to the following reasons.

- The pretraining task is to learn the matchability between the buggy program and the reference programs, so we need sufficient program pairs to input. 
- The finetuning task is to find the suspicious error locations by extracting the mismatched nodes matching to the reference program, so we need the correct program with a highest simiality to get more accurate and valuable mismatched information.

Hope these can help you understand the two datasets.

**Comment by Eden-yy** [comment]
> Hi @Eden-yy,
> 
> Thank you for your attention to our work.
> 
> The difference between the two datasets is that in the pretraining dataset, we pair one buggy program with multiple reference programs of various similarities, while in the finetuning dataset, we only pair a buggy program with the most similar reference program. We use different datasets for pretraining and finetuning due to the following reasons.
> 
> * The pretraining task is to learn the matchability between the buggy program and the reference programs, so we need sufficient program pairs to input.
> * The finetuning task is to find the suspicious error locations by extracting the mismatched nodes matching to the reference program, so we need the correct program with a highest simiality to get more accurate and valuable mismatched information.
> 
> Hope these can help you understand the two datasets.

Thank you very much. I've actually been following your team's work for a while now! It is a pleasure to receive your reply!

Allow me to ask one more question,does the most similar pairs comes from the highest cosine similarity of the ASTNN embeddings?

**Comment by sqhan-Husky** [comment]
> Allow me to ask one more question,does the most similar pairs comes from the highest cosine similarity of the ASTNN embeddings?

@Eden-yy  Yes, you're right. Since ASTNN is a nice code representation method which integrates the syntax and semantic features into a code embedding, we apply this to find similar programs.

Feel free to ask any questions.

**Comment by Eden-yy** [comment]
Hello @sqhan-Husky , I apologize for any inconvenience caused. It has been a month since I last reached out to you for guidance. During this time, I have been diligently attempting to construct a graph dataset and fine-tune data according to the methods outlined in your paper, yet unfortunately, the training results have not been as satisfactory as I had hoped. I sincerely hope to receive your assistance and wonder if you would be willing to share your graph_data.npy file and the fine-tuned dataset with me. Thank you very much for your patience and support!

**Comment by sqhan-Husky** [comment]
Hi @Eden-yy, 

For the graph dataset, one important step is to construct an informative control flow graph for each program. You can follow Figure 3 in the paper and use [joern](https://github.com/joernio/joern) to achieve this. 

Our open-source materials should be sufficient to reproduce all our experiment results.
